# Generated by Django 3.0.14 on 2021-11-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=130)),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
