# Generated by Django 3.0.14 on 2021-11-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
